modified checking codes

diff --git a/generatevcf b/generatevcf
--- a/generatevcf
+++ b/generatevcf
@@ -14,28 +14,25 @@ cd $root
 source $root/src/environment.sh
 
 # Requires
-#module load samtools/1.3 java/1.8.0_40 tabix/0.2.6 bcftools/1.3 vcftools/0.1.13 python/2.7.3
+module load samtools/1.3 java/1.8.0_40 tabix/0.2.6 bcftools/1.3 vcftools/0.1.13 python/2.7.3
 unset pipefail
 unset error
 
-samtools --help 2>&1 > /dev/null || module load samtools/1.3 || echo "could not load samtools" >&2 && error="true"
+samtools --help 2>&1 > /dev/null || echo "could not load samtools" >&2 && error="true"
 
-bcftools --help 2>&1 > /dev/null || module load bcftools/1.3 || echo "could not load bcftools" >&2 && error="true"
+bcftools --help 2>&1 > /dev/null || echo "could not load bcftools" >&2 && error="true"
 
 tabix --help 2>&1 > /dev/null
 if [[ "$?" != "1" ]]; then
-	module load tabix
-	if [[ "$?" != "1" ]]; then
-		echo "could not load tabix" >&2
-		error="true"
-	fi
+	echo "could not load tabix" >&2
+	error="true"
 fi
 
-vcftools --help 2>&1 > /dev/null || module load vcftools/0.1.13 || echo "could not load vcftools" >&2 && error="true"
+vcftools --help 2>&1 > /dev/null || echo "could not load vcftools" >&2 && error="true"
 
-java -version 2>&1 > /dev/null || module load java || echo "could not load Java" >&2 && error="true"
+java -version 2>&1 > /dev/null || echo "could not load Java" >&2 && error="true"
 
-python --version 2>&1 > /dev/null || module load python/2.7.3 || echo "could not load Python 2.7" >&2 && error="true"
+python --version 2>&1 > /dev/null || echo "could not load Python 2.7" >&2 && error="true"
 
 if [[ $error == "true" ]]; then
 	exit 1
@@ -70,5 +67,3 @@ full_genotype $cultivar
 # It is also expedient to split the VCF by chromosome so that merges can be performed with some degree of parallelism.
 # This step is not necessary if a merge is not planned.
 clean_and_split_vcf $cultivar
-
-
