small bugfixes

diff --git a/generatetree b/generatetree
--- a/generatetree
+++ b/generatetree
@@ -14,6 +14,14 @@ root="$(dirname "$(readlink -f "$0")")"
 cd $root
 source $root/src/environment
 
+bcftools --help
+if ["echo $?" != "0"]; then
+	module load bcftools/1.3
+	if ["echo $?" != "0"]; then
+		echo "could not load bcftool module"
+
+
+
 # If VCFs have not been cleaned and split, warn the user
 unset error
 for cultivar in $cultivarlist; do
