testing new requirements tests. I hate tabix. It won't return 0 unless it indexes something

diff --git a/generatevcf b/generatevcf
--- a/generatevcf
+++ b/generatevcf
@@ -17,23 +17,10 @@ source $root/src/environment.sh
 #module load samtools/1.3 java/1.8.0_40 tabix/0.2.6 bcftools/1.3 vcftools/0.1.13 python/2.7.3
 unset pipefail
 unset error
-samtools --help > /dev/null
-if [[ "$?" != "0" ]]; then
-	module load samtools/1.3
-	if [[ "$?" != "0" ]]; then
-		echo "could not load samtools" >&2
-		error="true"
-	fi
-fi
 
-bcftools --help > /dev/null
-if [[ "$?" != "0" ]]; then
-	module load bcftools/1.3
-	if [[ "$?" != "0" ]]; then
-		echo "could not load bcftools" >&2
-		error="true"
-	fi
-fi
+samtools --help > /dev/null || module load samtools/1.3 || echo "could not load samtools" >&2 && error="true"
+
+bcftools --help > /dev/null || module load bcftools/1.3 || echo "could not load bcftools" >&2 && error="true"
 
 tabix --help 2> /dev/null
 if [[ "$?" != "1" ]]; then
@@ -44,32 +31,11 @@ if [[ "$?" != "1" ]]; then
 	fi
 fi
 
-vcftools --help > /dev/null
-if [[ "$?" != "0" ]]; then
-	module load vcftools/0.1.13
-	if [[ "$?" != "0" ]]; then
-		echo "could not load vcftools" >&2
-		error="true"
-	fi
-fi
+vcftools --help > /dev/null || module load vcftools/0.1.13 || echo "could not load vcftools" >&2 && error="true"
 
-java -h > /dev/null
-if [[ "$?" != "0" ]]; then
-	module load java
-	if [[ "$?" != "0" ]]; then
-		echo "could not load Java" >&2
-		error="true"
-	fi
-fi
+java -version > /dev/null || module load java || echo "could not load Java" >&2 && error="true"
 
-python --version > /dev/null
-if [[ "$?" != "0" ]]; then
-	module load python/2.7.3
-	if [[ "$?" != "0" ]]; then
-		echo "could not load Python 2.7" >&2
-		error="true"
-	fi
-fi
+python --version > /dev/null || module load python/2.7.3 || echo "could not load Python 2.7" >&2 && error="true"
 
 if [[ $error == "true" ]]; then
 	exit 1
