added module checking

diff --git a/generatevcf b/generatevcf
--- a/generatevcf
+++ b/generatevcf
@@ -11,6 +11,43 @@ root="$(pwd)"
 # Requires
 #module load samtools/1.3 java/1.8.0_40 tabix/0.2.6 bcftools/1.3 vcftools/0.1.13 python/2.7.3
 
+samtools --help
+if ["echo $?" != "0"]; then
+	module load samtools
+	if ["echo $?" != "0"]; then
+		echo "could not load samtools module"
+fi
+bcftools --help
+if ["echo $?" != "0"]; then
+	module load bcftools
+	if ["echo $?" != "0"]; then
+		echo "could not load bcftool module"
+fi
+tabix --help 
+if ["echo $?" != "1"]; then
+	module load tabix
+	if ["echo $?" != "1"]; then
+		echo "could not load tabix module"
+fi
+vcftools --help
+if ["echo $?" != "0"]; then
+	module load vcftools
+	if ["echo $?" != "0"]; then
+		echo "could not load vcftools"
+fi
+java -h
+if ["echo $?" != "0"]; then
+	module load java
+	if ["echo$?" != "0"]; then
+		echo "could not load java"
+fi
+python --version
+if ["echo $?" != "0"]; then
+	module load python/2.7.3
+	if ["echo $?" != "0"]; then
+		echo "could not load python 2.7.3"
+fi
+
 cd $root
 source $root/src/environment
 
