more bugfixes

diff --git a/generatetree b/generatetree
--- a/generatetree
+++ b/generatetree
@@ -14,12 +14,50 @@ root="$(dirname "$(readlink -f "$0")")"
 cd $root
 source $root/src/environment
 
-bcftools --help
+bcftools --help > /dev/null
 if ["echo $?" != "0"]; then
 	module load bcftools/1.3
 	if ["echo $?" != "0"]; then
-		echo "could not load bcftool module"
+		echo "could not load bcftools" >&2
+		error="true"
+	fi
+fi
 
+tabix --help > /dev/null
+if ["echo $?" != "1"]; then
+	module load tabix
+	if ["echo $?" != "1"]; then
+		echo "could not load tabix" >&2
+		error="true"
+	fi
+fi
+
+vcftools --help > /dev/null
+if ["echo $?" != "0"]; then
+	module load vcftools/0.1.13
+	if ["echo $?" != "0"]; then
+		echo "could not load vcftools" >&2
+		error="true"
+	fi
+fi
+
+python --version > /dev/null
+if ["echo $?" != "0"]; then
+	module load python/2.7.3
+	if ["echo $?" != "0"]; then
+		echo "could not load Python 2.7" >&2
+		error="true"
+	fi
+fi
+
+raxml -h > /dev/null
+if ["echo $?" != "0"]; then
+	module load raxml
+	if ["echo $?" != "0"]; then
+		echo "could not load RAxML" >&2
+		error="true"
+	fi
+fi
 
 
 # If VCFs have not been cleaned and split, warn the user
diff --git a/generatevcf b/generatevcf
--- a/generatevcf
+++ b/generatevcf
@@ -16,34 +16,34 @@ source $root/src/environment
 # Requires
 #module load samtools/1.3 java/1.8.0_40 tabix/0.2.6 bcftools/1.3 vcftools/0.1.13 python/2.7.3
 unset error
-samtools --help
+samtools --help > /dev/null
 if ["echo $?" != "0"]; then
 	module load samtools/1.3
 	if ["echo $?" != "0"]; then
-		echo "could not load samtools module" >&2
+		echo "could not load samtools" >&2
 		error="true"
 	fi
 fi
 
-bcftools --help
+bcftools --help > /dev/null
 if ["echo $?" != "0"]; then
 	module load bcftools/1.3
 	if ["echo $?" != "0"]; then
-		echo "could not load bcftool module" >&2
+		echo "could not load bcftools" >&2
 		error="true"
 	fi
 fi
 
-tabix --help
+tabix --help > /dev/null
 if ["echo $?" != "1"]; then
 	module load tabix
 	if ["echo $?" != "1"]; then
-		echo "could not load tabix module" >&2
+		echo "could not load tabix" >&2
 		error="true"
 	fi
 fi
 
-vcftools --help
+vcftools --help > /dev/null
 if ["echo $?" != "0"]; then
 	module load vcftools/0.1.13
 	if ["echo $?" != "0"]; then
@@ -52,20 +52,20 @@ if ["echo $?" != "0"]; then
 	fi
 fi
 
-java -h
+java -h > /dev/null
 if ["echo $?" != "0"]; then
 	module load java
 	if ["echo$?" != "0"]; then
-		echo "could not load java" >&2
+		echo "could not load Java" >&2
 		error="true"
 	fi
 fi
 
-python --version
+python --version > /dev/null
 if ["echo $?" != "0"]; then
 	module load python/2.7.3
 	if ["echo $?" != "0"]; then
-		echo "could not load python 2.7.3" >&2
+		echo "could not load Python 2.7" >&2
 		error="true"
 	fi
 fi
