may be bad commit

diff --git a/generatevcf b/generatevcf
--- a/generatevcf
+++ b/generatevcf
@@ -22,14 +22,14 @@ samtools --help >/dev/null 2>&1 || module load samtools/1.3 || (echo "could not 
 
 bcftools --help >/dev/null 2>&1 || module load bcftools/1.3 || (echo "could not load bcftools" >&2 && error="true")
 
-tabix --help >/dev/null 2>&1
-if [[ "$?" != "1" ]]; then
+#tabix --help >/dev/null 2>&1
+#if [[ "$?" != "1" ]]; then
 	module load tabix
-	if [[ "$?" != "1" ]]; then
-		echo "could not load tabix" >&2
-		error="true"
-	fi
-fi
+#	if [[ "$?" != "1" ]]; then
+#		echo "could not load tabix" >&2
+#		error="true"
+#	fi
+#fi
 
 vcftools --help >/dev/null 2>&1 || module load vcftools/0.1.13 || (echo "could not load vcftools" >&2 && error="true")
 
