thingy

diff --git a/generatetree b/generatetree
--- a/generatetree
+++ b/generatetree
@@ -19,14 +19,14 @@ module load bcftools/1.3 tabix/0.2.6 vcftools/0.1.13 python/2.7.3 raxml >/dev/nu
 unset pipefail
 
 bcftools --help >/dev/null bcftools --help >/dev/null 2>&1 || (echo "could not load bcftools" >&2 && error="true")
-
-tabix --help >/dev/null 
+set +e
+tabix --help >/dev/null
 2>&1
 if [[ "$?" != "1" ]]; then
-        echo "could not load tabix" >&2
-        error="true"
+	echo "could not load tabix" >&2
+	error="true"
 fi
-
+set -e
 vcftools --help >/dev/null 2>&1 || (echo "could not load vcftools" >&2 && error="true")
 
 python --version >/dev/null 2>&1 || (echo "could not load Python 2.7" >&2 && error="true")
