made some changes that got generatevcf running on an Ubuntu 14.04 LTS Jetstream

diff --git a/generatevcf b/generatevcf
--- a/generatevcf
+++ b/generatevcf
@@ -15,22 +15,22 @@ source $root/src/environment.sh
 
 # Requires
 echo "Checking for required software"
-. /etc/profile.d/modules.sh >/dev/null 2>&1
-module load samtools java/1.8.0_40 tabix/0.2.6 bcftools/1.3 vcftools/0.1.13 python/2.7.3 >/dev/null 2>&1
+#. /etc/profile.d/modules.sh >/dev/null 2>&1
+#module load samtools java/1.8.0_40 tabix/0.2.6 bcftools/1.3 vcftools/0.1.13 python/2.7.3 >/dev/null 2>&1
 error=""
 
-samtools --help >/dev/null 2>&1 || (echo "could not load samtools" >&2 && error="true")
-bcftools --help >/dev/null 2>&1 || (echo "could not load bcftools" >&2 && error="true")
-vcftools --help >/dev/null 2>&1 || (echo "could not load vcftools" >&2 && error="true")
-java -version >/dev/null 2>&1 || (echo "could not load Java" >&2 && error="true")
-python --version >/dev/null 2>&1 || (echo "could not load Python 2.7" >&2 && error="true")
-set +e
-tabix --help >/dev/null 2>&1
-if [[ "$?" != "1" ]]; then
-	echo "could not load tabix" >&2
-	error="true"
-fi
-set -e
+#samtools --help >/dev/null 2>&1 || (echo "could not load samtools" >&2 && error="true")
+#bcftools --help >/dev/null 2>&1 || (echo "could not load bcftools" >&2 && error="true")
+#vcftools --help >/dev/null 2>&1 || (echo "could not load vcftools" >&2 && error="true")
+#java -version >/dev/null 2>&1 || (echo "could not load Java" >&2 && error="true")
+#python --version >/dev/null 2>&1 || (echo "could not load Python 2.7" >&2 && error="true")
+#set +e
+#tabix --help >/dev/null 2>&1
+#if [[ "$?" != "1" ]]; then
+#	echo "could not load tabix" >&2
+#	error="true"
+#fi
+#set -e
 
 if [[ -n "$error" ]]; then
 	echo "Exiting due to lack of software" >&2
